spring.application.name=corp

spring.datasource.url=jdbc:postgresql://localhost:5432/phonebook
spring.datasource.username=admin
spring.datasource.password=secret1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# debug spring data
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true